{"environment": "", "features": [{"name": "purchase", "status": "failed", "duration": 79.85741996765137, "filename": "features/purchase merchandise.feature", "scenarios": [{"name": "1 Successful Login", "duration": 36.10544943809509, "status": "failed", "tags": [], "filename": "features/purchase merchandise.feature", "feature": "purchase", "id_feature": 12649, "steps": [{"step_type": "given", "name": "I am on the Demo Login Page", "text": "None", "status": "passed", "duration": 1.9593369960784912, "hash": 36788559, "index": 0}, {"step_type": "when", "name": "I fill the account information for account StandardUser into the Username field and the Password field", "text": "None", "status": "passed", "duration": 6.256342649459839, "hash": 19476994, "index": 1}, {"step_type": "when", "name": "I click the Login Button", "text": "None", "status": "passed", "duration": 3.1873652935028076, "hash": 79821218, "index": 2}, {"step_type": "then", "name": "I am redirected to the Demo Main Page", "text": "None", "status": "passed", "duration": 3.1249120235443115, "hash": 61662335, "index": 3}, {"step_type": "then", "name": "I verify the App Logo exists", "text": "None", "status": "failed", "duration": 21.577492475509644, "error_msg": "HTTPConnectionPool(host='localhost', port=55565): Max retries exceeded with url: /session/0afc1bf0a1991a2c30346176f8afe94c/screenshot (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C8A6401730>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))", "error_lines": ["  File \"C:\\Users\\MOHAMAD SHARUK\\Automation\\Assessment\\.venv\\Lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n", "  File \"C:\\Users\\MOHAMAD SHARUK\\Automation\\Assessment\\.venv\\Lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n", "  File \"features\\steps\\Scenario.py\", line 67, in app_logo\n    take_screenshot(context.driver, \"I verify the App Logo exists\")\n", "  File \"features\\steps\\Scenario.py\", line 14, in take_screenshot\n    driver.save_screenshot(filename)\n", "  File \"C:\\Users\\MOHAMAD SHARUK\\Automation\\Assessment\\.venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 829, in save_screenshot\n    return self.get_screenshot_as_file(filename)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n", "  File \"C:\\Users\\MOHAMAD SHARUK\\Automation\\Assessment\\.venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 805, in get_screenshot_as_file\n    png = self.get_screenshot_as_png()\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n", "  File \"C:\\Users\\MOHAMAD SHARUK\\Automation\\Assessment\\.venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 839, in get_screenshot_as_png\n    return b64decode(self.get_screenshot_as_base64().encode(\"ascii\"))\n                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n", "  File \"C:\\Users\\MOHAMAD SHARUK\\Automation\\Assessment\\.venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 850, in get_screenshot_as_base64\n    return self.execute(Command.SCREENSHOT)[\"value\"]\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n", "  File \"C:\\Users\\MOHAMAD SHARUK\\Automation\\Assessment\\.venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 352, in execute\n    response = self.command_executor.execute(driver_command, params)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n", "  File \"C:\\Users\\MOHAMAD SHARUK\\Automation\\Assessment\\.venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\remote_connection.py\", line 302, in execute\n    return self._request(command_info[0], url, body=data)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n", "  File \"C:\\Users\\MOHAMAD SHARUK\\Automation\\Assessment\\.venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\remote_connection.py\", line 322, in _request\n    response = self._conn.request(method, url, body=body, headers=headers)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n", "  File \"C:\\Users\\MOHAMAD SHARUK\\Automation\\Assessment\\.venv\\Lib\\site-packages\\urllib3\\_request_methods.py\", line 136, in request\n    return self.request_encode_url(\n           ^^^^^^^^^^^^^^^^^^^^^^^^\n", "  File \"C:\\Users\\MOHAMAD SHARUK\\Automation\\Assessment\\.venv\\Lib\\site-packages\\urllib3\\_request_methods.py\", line 183, in request_encode_url\n    return self.urlopen(method, url, **extra_kw)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n", "  File \"C:\\Users\\MOHAMAD SHARUK\\Automation\\Assessment\\.venv\\Lib\\site-packages\\urllib3\\poolmanager.py\", line 443, in urlopen\n    response = conn.urlopen(method, u.request_uri, **kw)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n", "  File \"C:\\Users\\MOHAMAD SHARUK\\Automation\\Assessment\\.venv\\Lib\\site-packages\\urllib3\\connectionpool.py\", line 873, in urlopen\n    return self.urlopen(\n           ^^^^^^^^^^^^^\n", "  File \"C:\\Users\\MOHAMAD SHARUK\\Automation\\Assessment\\.venv\\Lib\\site-packages\\urllib3\\connectionpool.py\", line 873, in urlopen\n    return self.urlopen(\n           ^^^^^^^^^^^^^\n", "  File \"C:\\Users\\MOHAMAD SHARUK\\Automation\\Assessment\\.venv\\Lib\\site-packages\\urllib3\\connectionpool.py\", line 873, in urlopen\n    return self.urlopen(\n           ^^^^^^^^^^^^^\n", "  File \"C:\\Users\\MOHAMAD SHARUK\\Automation\\Assessment\\.venv\\Lib\\site-packages\\urllib3\\connectionpool.py\", line 843, in urlopen\n    retries = retries.increment(\n              ^^^^^^^^^^^^^^^^^^\n", "  File \"C:\\Users\\MOHAMAD SHARUK\\Automation\\Assessment\\.venv\\Lib\\site-packages\\urllib3\\util\\retry.py\", line 519, in increment\n    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]\n    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n"], "hash": 20158296, "index": 4}], "outline_index": 0, "background": {"duration": 0.0, "steps": []}, "error_msg": ["HTTPConnectionPool(host='localhost', port=55565): Max retries exceeded with url: /session/0afc1bf0a1991a2c30346176f8afe94c/screenshot (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C8A6401730>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))"], "error_lines": ["  File \"C:\\Users\\MOHAMAD SHARUK\\Automation\\Assessment\\.venv\\Lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n", "  File \"C:\\Users\\MOHAMAD SHARUK\\Automation\\Assessment\\.venv\\Lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n", "  File \"features\\steps\\Scenario.py\", line 67, in app_logo\n    take_screenshot(context.driver, \"I verify the App Logo exists\")\n", "  File \"features\\steps\\Scenario.py\", line 14, in take_screenshot\n    driver.save_screenshot(filename)\n", "  File \"C:\\Users\\MOHAMAD SHARUK\\Automation\\Assessment\\.venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 829, in save_screenshot\n    return self.get_screenshot_as_file(filename)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n", "  File \"C:\\Users\\MOHAMAD SHARUK\\Automation\\Assessment\\.venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 805, in get_screenshot_as_file\n    png = self.get_screenshot_as_png()\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n", "  File \"C:\\Users\\MOHAMAD SHARUK\\Automation\\Assessment\\.venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 839, in get_screenshot_as_png\n    return b64decode(self.get_screenshot_as_base64().encode(\"ascii\"))\n                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n", "  File \"C:\\Users\\MOHAMAD SHARUK\\Automation\\Assessment\\.venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 850, in get_screenshot_as_base64\n    return self.execute(Command.SCREENSHOT)[\"value\"]\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n", "  File \"C:\\Users\\MOHAMAD SHARUK\\Automation\\Assessment\\.venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 352, in execute\n    response = self.command_executor.execute(driver_command, params)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n", "  File \"C:\\Users\\MOHAMAD SHARUK\\Automation\\Assessment\\.venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\remote_connection.py\", line 302, in execute\n    return self._request(command_info[0], url, body=data)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n", "  File \"C:\\Users\\MOHAMAD SHARUK\\Automation\\Assessment\\.venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\remote_connection.py\", line 322, in _request\n    response = self._conn.request(method, url, body=body, headers=headers)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n", "  File \"C:\\Users\\MOHAMAD SHARUK\\Automation\\Assessment\\.venv\\Lib\\site-packages\\urllib3\\_request_methods.py\", line 136, in request\n    return self.request_encode_url(\n           ^^^^^^^^^^^^^^^^^^^^^^^^\n", "  File \"C:\\Users\\MOHAMAD SHARUK\\Automation\\Assessment\\.venv\\Lib\\site-packages\\urllib3\\_request_methods.py\", line 183, in request_encode_url\n    return self.urlopen(method, url, **extra_kw)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n", "  File \"C:\\Users\\MOHAMAD SHARUK\\Automation\\Assessment\\.venv\\Lib\\site-packages\\urllib3\\poolmanager.py\", line 443, in urlopen\n    response = conn.urlopen(method, u.request_uri, **kw)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n", "  File \"C:\\Users\\MOHAMAD SHARUK\\Automation\\Assessment\\.venv\\Lib\\site-packages\\urllib3\\connectionpool.py\", line 873, in urlopen\n    return self.urlopen(\n           ^^^^^^^^^^^^^\n", "  File \"C:\\Users\\MOHAMAD SHARUK\\Automation\\Assessment\\.venv\\Lib\\site-packages\\urllib3\\connectionpool.py\", line 873, in urlopen\n    return self.urlopen(\n           ^^^^^^^^^^^^^\n", "  File \"C:\\Users\\MOHAMAD SHARUK\\Automation\\Assessment\\.venv\\Lib\\site-packages\\urllib3\\connectionpool.py\", line 873, in urlopen\n    return self.urlopen(\n           ^^^^^^^^^^^^^\n", "  File \"C:\\Users\\MOHAMAD SHARUK\\Automation\\Assessment\\.venv\\Lib\\site-packages\\urllib3\\connectionpool.py\", line 843, in urlopen\n    retries = retries.increment(\n              ^^^^^^^^^^^^^^^^^^\n", "  File \"C:\\Users\\MOHAMAD SHARUK\\Automation\\Assessment\\.venv\\Lib\\site-packages\\urllib3\\util\\retry.py\", line 519, in increment\n    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]\n    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n"], "error_step": {"step_type": "then", "name": "I verify the App Logo exists", "text": "None", "status": "failed", "duration": 21.577492475509644, "error_msg": "HTTPConnectionPool(host='localhost', port=55565): Max retries exceeded with url: /session/0afc1bf0a1991a2c30346176f8afe94c/screenshot (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C8A6401730>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))", "error_lines": ["  File \"C:\\Users\\MOHAMAD SHARUK\\Automation\\Assessment\\.venv\\Lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n", "  File \"C:\\Users\\MOHAMAD SHARUK\\Automation\\Assessment\\.venv\\Lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n", "  File \"features\\steps\\Scenario.py\", line 67, in app_logo\n    take_screenshot(context.driver, \"I verify the App Logo exists\")\n", "  File \"features\\steps\\Scenario.py\", line 14, in take_screenshot\n    driver.save_screenshot(filename)\n", "  File \"C:\\Users\\MOHAMAD SHARUK\\Automation\\Assessment\\.venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 829, in save_screenshot\n    return self.get_screenshot_as_file(filename)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n", "  File \"C:\\Users\\MOHAMAD SHARUK\\Automation\\Assessment\\.venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 805, in get_screenshot_as_file\n    png = self.get_screenshot_as_png()\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n", "  File \"C:\\Users\\MOHAMAD SHARUK\\Automation\\Assessment\\.venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 839, in get_screenshot_as_png\n    return b64decode(self.get_screenshot_as_base64().encode(\"ascii\"))\n                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n", "  File \"C:\\Users\\MOHAMAD SHARUK\\Automation\\Assessment\\.venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 850, in get_screenshot_as_base64\n    return self.execute(Command.SCREENSHOT)[\"value\"]\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n", "  File \"C:\\Users\\MOHAMAD SHARUK\\Automation\\Assessment\\.venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 352, in execute\n    response = self.command_executor.execute(driver_command, params)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n", "  File \"C:\\Users\\MOHAMAD SHARUK\\Automation\\Assessment\\.venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\remote_connection.py\", line 302, in execute\n    return self._request(command_info[0], url, body=data)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n", "  File \"C:\\Users\\MOHAMAD SHARUK\\Automation\\Assessment\\.venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\remote_connection.py\", line 322, in _request\n    response = self._conn.request(method, url, body=body, headers=headers)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n", "  File \"C:\\Users\\MOHAMAD SHARUK\\Automation\\Assessment\\.venv\\Lib\\site-packages\\urllib3\\_request_methods.py\", line 136, in request\n    return self.request_encode_url(\n           ^^^^^^^^^^^^^^^^^^^^^^^^\n", "  File \"C:\\Users\\MOHAMAD SHARUK\\Automation\\Assessment\\.venv\\Lib\\site-packages\\urllib3\\_request_methods.py\", line 183, in request_encode_url\n    return self.urlopen(method, url, **extra_kw)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n", "  File \"C:\\Users\\MOHAMAD SHARUK\\Automation\\Assessment\\.venv\\Lib\\site-packages\\urllib3\\poolmanager.py\", line 443, in urlopen\n    response = conn.urlopen(method, u.request_uri, **kw)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n", "  File \"C:\\Users\\MOHAMAD SHARUK\\Automation\\Assessment\\.venv\\Lib\\site-packages\\urllib3\\connectionpool.py\", line 873, in urlopen\n    return self.urlopen(\n           ^^^^^^^^^^^^^\n", "  File \"C:\\Users\\MOHAMAD SHARUK\\Automation\\Assessment\\.venv\\Lib\\site-packages\\urllib3\\connectionpool.py\", line 873, in urlopen\n    return self.urlopen(\n           ^^^^^^^^^^^^^\n", "  File \"C:\\Users\\MOHAMAD SHARUK\\Automation\\Assessment\\.venv\\Lib\\site-packages\\urllib3\\connectionpool.py\", line 873, in urlopen\n    return self.urlopen(\n           ^^^^^^^^^^^^^\n", "  File \"C:\\Users\\MOHAMAD SHARUK\\Automation\\Assessment\\.venv\\Lib\\site-packages\\urllib3\\connectionpool.py\", line 843, in urlopen\n    retries = retries.increment(\n              ^^^^^^^^^^^^^^^^^^\n", "  File \"C:\\Users\\MOHAMAD SHARUK\\Automation\\Assessment\\.venv\\Lib\\site-packages\\urllib3\\util\\retry.py\", line 519, in increment\n    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]\n    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n"], "hash": 20158296, "index": 4}, "error_background": false, "id_hash": 51547852}, {"name": "2 Failed Login", "duration": 21.203546047210693, "status": "failed", "tags": [], "filename": "features/purchase merchandise.feature", "feature": "purchase", "id_feature": 12649, "steps": [{"step_type": "given", "name": "I am on the Demo Login Page", "text": "None", "status": "passed", "duration": 1.7352499961853027, "hash": 36788559, "index": 0}, {"step_type": "when", "name": "I fill the account information for account LockedOutUser into the Username field and the Password field", "text": "None", "status": "passed", "duration": 6.277458190917969, "hash": 95026348, "index": 1}, {"step_type": "when", "name": "I click the Login Button", "text": "None", "status": "passed", "duration": 3.1468255519866943, "hash": 79821218, "index": 2}, {"step_type": "then", "name": "I verify the Error Message contains the text \"Sorry, this user has been banned. \"", "text": "None", "status": "failed", "duration": 10.044012308120728, "error_msg": "Message: no such element: Unable to locate element: {\"method\":\"css selector\",\"selector\":\".error-message-container error\"}\n                  (Session info: chrome=127.0.6533.100); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception\n                Stacktrace:\n                \tGetHandleVerifier [0x00007FF6A4C39632+30946]\n                \t(No symbol) [0x00007FF6A4BEE3C9]\n                \t(No symbol) [0x00007FF6A4AE6FDA]\n                \t(No symbol) [0x00007FF6A4B3822C]\n                \t(No symbol) [0x00007FF6A4B3850C]\n                \t(No symbol) [0x00007FF6A4B7DCB7]\n                \t(No symbol) [0x00007FF6A4B5CAAF]\n                \t(No symbol) [0x00007FF6A4B7B041]\n                \t(No symbol) [0x00007FF6A4B5C813]\n                \t(No symbol) [0x00007FF6A4B2A6E5]\n                \t(No symbol) [0x00007FF6A4B2B021]\n                \tGetHandleVerifier [0x00007FF6A4D6F83D+1301229]\n                \tGetHandleVerifier [0x00007FF6A4D7BDB7+1351783]\n                \tGetHandleVerifier [0x00007FF6A4D72A03+1313971]\n                \tGetHandleVerifier [0x00007FF6A4C6DD06+245686]\n                \t(No symbol) [0x00007FF6A4BF758F]\n                \t(No symbol) [0x00007FF6A4BF3804]\n                \t(No symbol) [0x00007FF6A4BF3992]\n                \t(No symbol) [0x00007FF6A4BEA3EF]\n                \tBaseThreadInitThunk [0x00007FFE3B637374+20]\n                \tRtlUserThreadStart [0x00007FFE3D23CC91+33]", "error_lines": ["  File \"C:\\Users\\MOHAMAD SHARUK\\Automation\\Assessment\\.venv\\Lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n", "  File \"C:\\Users\\MOHAMAD SHARUK\\Automation\\Assessment\\.venv\\Lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n", "  File \"features\\steps\\Scenario.py\", line 71, in error_message\n    error = context.driver.find_element(By.CLASS_NAME,'error-message-container error').text\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n", "  File \"C:\\Users\\MOHAMAD SHARUK\\Automation\\Assessment\\.venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 748, in find_element\n    return self.execute(Command.FIND_ELEMENT, {\"using\": by, \"value\": value})[\"value\"]\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n", "  File \"C:\\Users\\MOHAMAD SHARUK\\Automation\\Assessment\\.venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 354, in execute\n    self.error_handler.check_response(response)\n", "  File \"C:\\Users\\MOHAMAD SHARUK\\Automation\\Assessment\\.venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n"], "hash": 95600288, "index": 3}], "outline_index": 0, "background": {"duration": 0.0, "steps": []}, "error_msg": ["Message: no such element: Unable to locate element: {\"method\":\"css selector\",\"selector\":\".error-message-container error\"}", "                  (Session info: chrome=127.0.6533.100); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception", "                Stacktrace:", "                \tGetHandleVerifier [0x00007FF6A4C39632+30946]", "                \t(No symbol) [0x00007FF6A4BEE3C9]", "                \t(No symbol) [0x00007FF6A4AE6FDA]", "                \t(No symbol) [0x00007FF6A4B3822C]", "                \t(No symbol) [0x00007FF6A4B3850C]", "                \t(No symbol) [0x00007FF6A4B7DCB7]", "                \t(No symbol) [0x00007FF6A4B5CAAF]", "                \t(No symbol) [0x00007FF6A4B7B041]", "                \t(No symbol) [0x00007FF6A4B5C813]", "                \t(No symbol) [0x00007FF6A4B2A6E5]", "                \t(No symbol) [0x00007FF6A4B2B021]", "                \tGetHandleVerifier [0x00007FF6A4D6F83D+1301229]", "                \tGetHandleVerifier [0x00007FF6A4D7BDB7+1351783]", "                \tGetHandleVerifier [0x00007FF6A4D72A03+1313971]", "                \tGetHandleVerifier [0x00007FF6A4C6DD06+245686]", "                \t(No symbol) [0x00007FF6A4BF758F]", "                \t(No symbol) [0x00007FF6A4BF3804]", "                \t(No symbol) [0x00007FF6A4BF3992]", "                \t(No symbol) [0x00007FF6A4BEA3EF]", "                \tBaseThreadInitThunk [0x00007FFE3B637374+20]", "                \tRtlUserThreadStart [0x00007FFE3D23CC91+33]"], "error_lines": ["  File \"C:\\Users\\MOHAMAD SHARUK\\Automation\\Assessment\\.venv\\Lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n", "  File \"C:\\Users\\MOHAMAD SHARUK\\Automation\\Assessment\\.venv\\Lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n", "  File \"features\\steps\\Scenario.py\", line 71, in error_message\n    error = context.driver.find_element(By.CLASS_NAME,'error-message-container error').text\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n", "  File \"C:\\Users\\MOHAMAD SHARUK\\Automation\\Assessment\\.venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 748, in find_element\n    return self.execute(Command.FIND_ELEMENT, {\"using\": by, \"value\": value})[\"value\"]\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n", "  File \"C:\\Users\\MOHAMAD SHARUK\\Automation\\Assessment\\.venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 354, in execute\n    self.error_handler.check_response(response)\n", "  File \"C:\\Users\\MOHAMAD SHARUK\\Automation\\Assessment\\.venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n"], "error_step": {"step_type": "then", "name": "I verify the Error Message contains the text \"Sorry, this user has been banned. \"", "text": "None", "status": "failed", "duration": 10.044012308120728, "error_msg": "Message: no such element: Unable to locate element: {\"method\":\"css selector\",\"selector\":\".error-message-container error\"}\n                  (Session info: chrome=127.0.6533.100); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception\n                Stacktrace:\n                \tGetHandleVerifier [0x00007FF6A4C39632+30946]\n                \t(No symbol) [0x00007FF6A4BEE3C9]\n                \t(No symbol) [0x00007FF6A4AE6FDA]\n                \t(No symbol) [0x00007FF6A4B3822C]\n                \t(No symbol) [0x00007FF6A4B3850C]\n                \t(No symbol) [0x00007FF6A4B7DCB7]\n                \t(No symbol) [0x00007FF6A4B5CAAF]\n                \t(No symbol) [0x00007FF6A4B7B041]\n                \t(No symbol) [0x00007FF6A4B5C813]\n                \t(No symbol) [0x00007FF6A4B2A6E5]\n                \t(No symbol) [0x00007FF6A4B2B021]\n                \tGetHandleVerifier [0x00007FF6A4D6F83D+1301229]\n                \tGetHandleVerifier [0x00007FF6A4D7BDB7+1351783]\n                \tGetHandleVerifier [0x00007FF6A4D72A03+1313971]\n                \tGetHandleVerifier [0x00007FF6A4C6DD06+245686]\n                \t(No symbol) [0x00007FF6A4BF758F]\n                \t(No symbol) [0x00007FF6A4BF3804]\n                \t(No symbol) [0x00007FF6A4BF3992]\n                \t(No symbol) [0x00007FF6A4BEA3EF]\n                \tBaseThreadInitThunk [0x00007FFE3B637374+20]\n                \tRtlUserThreadStart [0x00007FFE3D23CC91+33]", "error_lines": ["  File \"C:\\Users\\MOHAMAD SHARUK\\Automation\\Assessment\\.venv\\Lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n", "  File \"C:\\Users\\MOHAMAD SHARUK\\Automation\\Assessment\\.venv\\Lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n", "  File \"features\\steps\\Scenario.py\", line 71, in error_message\n    error = context.driver.find_element(By.CLASS_NAME,'error-message-container error').text\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n", "  File \"C:\\Users\\MOHAMAD SHARUK\\Automation\\Assessment\\.venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 748, in find_element\n    return self.execute(Command.FIND_ELEMENT, {\"using\": by, \"value\": value})[\"value\"]\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n", "  File \"C:\\Users\\MOHAMAD SHARUK\\Automation\\Assessment\\.venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 354, in execute\n    self.error_handler.check_response(response)\n", "  File \"C:\\Users\\MOHAMAD SHARUK\\Automation\\Assessment\\.venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n"], "hash": 95600288, "index": 3}, "error_background": false, "id_hash": 7777276}, {"name": "3 Order a product", "duration": 22.54842448234558, "status": "failed", "tags": [], "filename": "features/purchase merchandise.feature", "feature": "purchase", "id_feature": 12649, "steps": [{"step_type": "given", "name": "I am on the inventory page", "text": "None", "status": "passed", "duration": 0.1185157299041748, "hash": 20995446, "index": 0}, {"step_type": "when", "name": "user sorts products from high price to low price", "text": "None", "status": "passed", "duration": 5.2297163009643555, "hash": 14676213, "index": 1}, {"step_type": "when", "name": "user adds highest priced product", "text": "None", "status": "passed", "duration": 2.164306163787842, "hash": 31648473, "index": 2}, {"step_type": "when", "name": "user clicks on cart", "text": "None", "status": "passed", "duration": 2.1462008953094482, "hash": 41798981, "index": 3}, {"step_type": "when", "name": "user clicks on checkout", "text": "None", "status": "passed", "duration": 2.1587204933166504, "hash": 29831809, "index": 4}, {"step_type": "when", "name": "user enters first name Alice", "text": "None", "status": "passed", "duration": 2.147434949874878, "hash": 74098550, "index": 5}, {"step_type": "when", "name": "user enters last name Doe", "text": "None", "status": "passed", "duration": 2.139564275741577, "hash": 14283019, "index": 6}, {"step_type": "when", "name": "user enters zip code 592", "text": "None", "status": "passed", "duration": 2.135784149169922, "hash": 7683233, "index": 7}, {"step_type": "when", "name": "user clicks Continue button", "text": "None", "status": "passed", "duration": 2.133434534072876, "hash": 10012680, "index": 8}, {"step_type": "then", "name": "I verify in Checkout overview page if the total amount for the added item is $49.99", "text": "None", "status": "passed", "duration": 0.026000499725341797, "hash": 12149801, "index": 9}, {"step_type": "when", "name": "user clicks Finish button", "text": "None", "status": "passed", "duration": 2.128746509552002, "hash": 45220093, "index": 10}, {"step_type": "then", "name": "Thank You header is shown in Checkout Complete page", "text": "None", "status": "failed", "duration": 0.019999980926513672, "error_msg": "", "error_lines": ["  File \"C:\\Users\\MOHAMAD SHARUK\\Automation\\Assessment\\.venv\\Lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n", "  File \"C:\\Users\\MOHAMAD SHARUK\\Automation\\Assessment\\.venv\\Lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n", "  File \"features\\steps\\Scenario.py\", line 184, in complete_page\n    assert \"Thank You\" in text\n           ^^^^^^^^^^^^^^^^^^^\n"], "hash": 91590856, "index": 11}], "outline_index": 0, "background": {"duration": 0.0, "steps": []}, "error_msg": [], "error_lines": ["  File \"C:\\Users\\MOHAMAD SHARUK\\Automation\\Assessment\\.venv\\Lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n", "  File \"C:\\Users\\MOHAMAD SHARUK\\Automation\\Assessment\\.venv\\Lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n", "  File \"features\\steps\\Scenario.py\", line 184, in complete_page\n    assert \"Thank You\" in text\n           ^^^^^^^^^^^^^^^^^^^\n"], "error_step": {"step_type": "then", "name": "Thank You header is shown in Checkout Complete page", "text": "None", "status": "failed", "duration": 0.019999980926513672, "error_msg": "", "error_lines": ["  File \"C:\\Users\\MOHAMAD SHARUK\\Automation\\Assessment\\.venv\\Lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n", "  File \"C:\\Users\\MOHAMAD SHARUK\\Automation\\Assessment\\.venv\\Lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n", "  File \"features\\steps\\Scenario.py\", line 184, in complete_page\n    assert \"Thank You\" in text\n           ^^^^^^^^^^^^^^^^^^^\n"], "hash": 91590856, "index": 11}, "error_background": false, "id_hash": 25396420}], "background": {}, "id": 12649}], "steps_definition": {"20158296": "I verify the App Logo exists", "36788559": "I am on the Demo Login Page", "19476994": "I fill the account information for account StandardUser into the Username field and the Password field", "79821218": "I click the Login Button", "61662335": "I am redirected to the Demo Main Page", "95600288": "I verify the Error Message contains the text \"Sorry, this user has been banned. \"", "95026348": "I fill the account information for account LockedOutUser into the Username field and the Password field", "91590856": "Thank You header is shown in Checkout Complete page", "20995446": "I am on the inventory page", "14676213": "user sorts products from high price to low price", "31648473": "user adds highest priced product", "41798981": "user clicks on cart", "29831809": "user clicks on checkout", "74098550": "user enters first name Alice", "14283019": "user enters last name Doe", "7683233": "user enters zip code 592", "10012680": "user clicks Continue button", "12149801": "I verify in Checkout overview page if the total amount for the added item is $49.99", "45220093": "user clicks Finish button"}}